--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

CREATE DATABASE payment;

\c payment;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    id bigint NOT NULL,
    enabled boolean NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    merchant_id bigint,
    CONSTRAINT account_role_check CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('MERCHANT'::character varying)::text])))
);


ALTER TABLE public.account OWNER TO postgres;

--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: merchant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.merchant (
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    total_transaction_sum numeric(38,2) NOT NULL,
    CONSTRAINT merchant_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text])))
);


ALTER TABLE public.merchant OWNER TO postgres;

--
-- Name: merchant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.merchant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.merchant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    type character varying(31) NOT NULL,
    id bigint NOT NULL,
    customer_email character varying(255) NOT NULL,
    customer_phone character varying(255) NOT NULL,
    reference_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    uuid uuid NOT NULL,
    amount numeric(38,2),
    merchant_id bigint NOT NULL,
    created timestamp(6) without time zone NOT NULL,
    CONSTRAINT transaction_status_check CHECK (((status)::text = ANY ((ARRAY['APPROVED'::character varying, 'REVERSED'::character varying, 'REFUNDED'::character varying, 'ERROR'::character varying])::text[])))
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account (id, enabled, password, role, username, merchant_id) FROM stdin;
1	t	{bcrypt}$2a$10$R07yxcZTluekbSRtlLdfQeYH5GFUDa2Fhk0UORzztp71ScDS7HY22	ADMIN	admin	\N
2	t	{bcrypt}$2a$10$9s9n/CUQh.bWj/axEyU6RuPbSbdJdYTqpgs0K1J4Q2uOOCjgiSG22	ADMIN	admin1	\N
3	t	{bcrypt}$2a$10$dI69Wm3Hjdlpqrr3q9BX2uVA/Ar7N7MZi3MeHsvE/17FcKMa5JV1e	ADMIN	admin2	\N
4	t	{bcrypt}$2a$10$NCas1YfDUlRetxFKQSAhau0rEJQredLJjaCYiQeWYJd24dIII3wiW	MERCHANT	merchant	1
5	t	{bcrypt}$2a$10$giOOZ2ATH.qtILdpr/FM2u2KlvbEcxo9yx1XeBwqcqFg6C0vBfXJK	MERCHANT	merchant1	2
6	t	{bcrypt}$2a$10$ot4uXLaFJsZVpvhc0dYWte4M0flQJ423mWsZZz8j6EtpVBqRENQki	MERCHANT	merchant2	3
8	t	{bcrypt}$2a$10$WjBVtZhXxS2rizQ9c4DD1.sUUdIF43XK0k1ioKYs9yyW5TjBzmpBK	MERCHANT	merchant4	\N
7	t	{bcrypt}$2a$10$EEvnwtKCTNHQyWDybI6vwuY59RjhXCo22NFS5bTQzJ1L6e3doxw.q	MERCHANT	merchant3	6
\.


--
-- Data for Name: merchant; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.merchant (id, description, email, name, status, total_transaction_sum) FROM stdin;
3	This the merchant 22	merchant2@merchant.com	The SECOND merchant	ACTIVE	0.00
2	This the merchant 111	merchant1@merchant.com	The ONE merchant	ACTIVE	0.00
6	This is the merchant 33	merchant3@merchant.com	The THIRD merchant	ACTIVE	0.00
1	This is the merchant	merchant@merchant.com	The merchant	ACTIVE	20.69
\.


--
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaction (type, id, customer_email, customer_phone, reference_id, status, uuid, amount, merchant_id, created) FROM stdin;
\.


--
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_id_seq', 8, true);


--
-- Name: merchant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.merchant_id_seq', 6, true);


--
-- Name: transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_id_seq', 14, true);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: merchant merchant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.merchant
    ADD CONSTRAINT merchant_pkey PRIMARY KEY (id);


--
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);


--
-- Name: merchant uk22hw5xdmw9ehbp92kr3h9pbh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.merchant
    ADD CONSTRAINT uk22hw5xdmw9ehbp92kr3h9pbh UNIQUE (email);


--
-- Name: account uk5y4qonxqvfnjtjp8ync927ncn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uk5y4qonxqvfnjtjp8ync927ncn UNIQUE (merchant_id);


--
-- Name: account ukgex1lmaqpg0ir5g1f5eftyaa1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT ukgex1lmaqpg0ir5g1f5eftyaa1 UNIQUE (username);


--
-- Name: merchant ukhpejy4i1nk4u3251c6ba2pmpv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.merchant
    ADD CONSTRAINT ukhpejy4i1nk4u3251c6ba2pmpv UNIQUE (name);


--
-- Name: account fka7qfiwspw9s2fb7bvwyt9ea0h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fka7qfiwspw9s2fb7bvwyt9ea0h FOREIGN KEY (merchant_id) REFERENCES public.merchant(id);


--
-- Name: transaction fkcwlugq1eich0rct1w83pewkqc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fkcwlugq1eich0rct1w83pewkqc FOREIGN KEY (merchant_id) REFERENCES public.merchant(id);


--
-- PostgreSQL database dump complete
--

